on:
    push:
    pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the project
        uses: actions/checkout@v2
      - name: Initialize Python 3.9
        uses: actions/setup-python@v1
        with:
            python-version: 3.9
      - name: Install dependencies
        run: |
          pip install -e .
          pip install pytest
          pip install pytz
      - name: Run pytest
        run: pytest tests
